spring.datasource.url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
spring.datasource.username: root
spring.datasource.password: 980725
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
server.port: 8080
spring.thymeleaf.cache: false
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.check-template-location: true
spring.thymeleaf.suffix: .html
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.mode: HTML
spring.thymeleaf.servlet.content-type: text/html
spring.mvc.static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml

pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 403361459@qq.com #发送邮件的邮箱地址
    password:  rwnmzizynqxobggh #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 403361459@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 60s  # 连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池（使用lettuce，依赖中必须包含commons-pool2包）
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
